=== tfisher1226/ARIES/nam/nam-user/src/main/resources/schema/aries-validate-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<xs:schema 
	version="1.0"
	jaxb:version="2.0"
	elementFormDefault="qualified"
	attributeFormDefault="qualified"  
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:tns="http://www.aries.org/validate"
	targetNamespace="http://www.aries.org/validate">

	<xs:element name="checkpoints" type="tns:Checkpoints" />
	<xs:complexType name="Checkpoints">
		<xs:sequence>
			<xs:element name="version" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="enabled" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="checkpoint" type="tns:Checkpoint" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="checkpoint" type="tns:Checkpoint" />
	<xs:complexType name="Checkpoint">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="enabled" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="forced" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="condition" type="tns:Condition" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="condition" type="tns:Condition" />
	<xs:complexType name="Condition">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="enabled" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="forced" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<!--  
			<xs:element name="isTrue" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="isFalse" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="isEqual" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="notNull" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="notEmpty" type="xs:string" minOccurs="0" maxOccurs="1" />
			-->
			<xs:element name="expected" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="expression" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="exception" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="message" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="and" type="tns:And" minOccurs="0" maxOccurs="1" />
			<xs:element name="or" type="tns:Or" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:element name="and" type="tns:And"/>
	<xs:complexType name="And">
		<xs:sequence>
			<xs:element name="expression" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="or" type="tns:Or"/>
	<xs:complexType name="Or">
		<xs:sequence>
			<xs:element name="expression" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!--  
	<xs:element name="notNull" type="tns:NotNull"/>
	<xs:complexType name="NotNull">
		<xs:complexContent>
			<xs:extension base="tns:Condition">
				<xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="notEmpty" type="tns:NotEmpty"/>
	<xs:complexType name="NotEmpty">
		<xs:complexContent>
			<xs:extension base="tns:Condition">
				<xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	-->
</xs:schema>

=== tfisher1226/ARIES/redhat/jee-migration-example/jee-migration-example-service/src/main/resources/jee-migration-example-service-checks.xml
<?xml version="1.0" encoding="UTF-8"?>

<checkpoints
	xmlns="http://www.aries.org/validate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aries.org/validate file:/workspace/ARIES2/aries-validate/src/main/resources/schema/aries-validate-1.0.xsd">


	<checkpoint>
		<name>id</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Id must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>event</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Event must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$event/date</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Event/date must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$event/message</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Event/message must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>itemId</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>ItemId must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>item</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Item must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$item/id</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Item/id must be specified</message>
		</condition>
	</checkpoint>


</checkpoints>

=== tfisher1226/ARIES/admin/admin-model/src/main/resources/admin-checks.xml
<?xml version="1.0" encoding="UTF-8"?>

<checkpoints
	xmlns="http://www.aries.org/validate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aries.org/validate file:/workspace/ARIES/aries-validate/src/main/resources/schema/aries-validate-1.0.xsd">


	<checkpoint>
		<name>id</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>Id must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>userName</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>UserName must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>user</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/firstName</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User/firstName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/lastName</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User/lastName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/userName</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User/userName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/passwordHash</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User/passwordHash must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User/emailAddress must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/emailAddress/url</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User/emailAddress/url must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/roles</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>User must include one or more roles(s)</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>name</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>Name must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>skin</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>Skin must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$skin/name</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>Skin/name must be specified</message>
		</condition>
	</checkpoint>


</checkpoints>

=== tfisher1226/ARIES/nam/nam-client/src/main/resources/admin-client-checks.xml
<?xml version="1.0" encoding="UTF-8"?>

<checkpoints
	xmlns="http://www.aries.org/validate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aries.org/validate file:/workspace/ARIES/aries-validate/src/main/resources/schema/aries-validate-1.0.xsd">


	<checkpoint>
		<name>id</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Id must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>registration</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/userName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/userName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/passwordHash</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/passwordHash must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/name must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/name/lastName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/name/lastName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/name/firstName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/name/firstName must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/personName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/personName/lastName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/personName/lastName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/personName/firstName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/personName/firstName must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/emailAddress must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/emailAddress/url</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user/emailAddress/url must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$registration/user/roles</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Registration/user must include one or more roles(s)</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>userName</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>UserName must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>user</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>User must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/userName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/userName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/passwordHash</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/passwordHash must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/name must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/name/lastName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/name/lastName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/name/firstName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/name/firstName must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/personName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/personName/lastName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/personName/lastName must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/personName/firstName</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/personName/firstName must be specified</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/emailAddress must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/emailAddress/url</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User/emailAddress/url must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$user/roles</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>User must include one or more roles(s)</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>name</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Name must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>roleType</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>RoleType must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>role</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Role must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$role/name</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Role/name must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$role/roleType</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Role/roleType must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$role/permissions</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Role must include one or more permissions(s)</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>skin</name>
		<condition>
			<type>notNull</type>
			<exception>org.aries.AssertionFailure</exception>
			<message>Skin must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$skin/name</expression>
			<exception>org.aries.AssertionFailure</exception>
			<message>Skin/name must be specified</message>
		</condition>
	</checkpoint>


</checkpoints>

=== tfisher1226/ARIES/bookshop2/bookshop2-buyer/bookshop2-buyer-client/src/main/resources/bookshop2-buyer-client-checks.xml
<?xml version="1.0" encoding="UTF-8"?>

<checkpoints
	xmlns="http://www.aries.org/validate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.aries.org/validate file:/workspace/ARIES/aries-validate/src/main/resources/schema/aries-validate-1.0.xsd">


	<checkpoint>
		<name>orderRequestMessage</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>OrderRequestMessage must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$orderRequestMessage/order/books</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>OrderRequestMessage must include one or more books(s)</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>orderAcceptedMessage</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>OrderAcceptedMessage must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$orderAcceptedMessage/order/books</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>OrderAcceptedMessage must include one or more books(s)</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>orderRejectedMessage</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>OrderRejectedMessage must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$orderRejectedMessage/reason</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>OrderRejectedMessage/reason must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>purchaseAcceptedMessage</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseAcceptedMessage/order/books</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage must include one or more book(s)</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage/payment must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseAcceptedMessage/payment/amount</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage/payment/amount must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseAcceptedMessage/payment/currency</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage/payment/currency must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseAcceptedMessage/payment/salesTax</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage/payment/salesTax must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseAcceptedMessage/payment/total</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseAcceptedMessage/payment/total must be specified</message>
		</condition>
	</checkpoint>


	<checkpoint>
		<name>purchaseRejectedMessage</name>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseRejectedMessage/order/books</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage must include one or more book(s)</message>
		</condition>
		<condition>
			<type>notNull</type>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage/payment must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseRejectedMessage/payment/amount</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage/payment/amount must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseRejectedMessage/payment/currency</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage/payment/currency must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseRejectedMessage/payment/salesTax</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage/payment/salesTax must be specified</message>
		</condition>
		<condition>
			<type>notEmpty</type>
			<expression>$purchaseRejectedMessage/payment/total</expression>
			<exception>java.lang.IllegalArgumentException</exception>
			<message>PurchaseRejectedMessage/payment/total must be specified</message>
		</condition>
	</checkpoint>


</checkpoints>
